// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2xFgKPUk-llTYRr8uJNb3cSbB6HcZbUE',
    appId: '1:1000736909434:web:18cf6e100b04f13578f3c3',
    messagingSenderId: '1000736909434',
    projectId: 'merchant-pmck',
    authDomain: 'merchant-pmck.firebaseapp.com',
    storageBucket: 'merchant-pmck.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNP3ZMglGChv_QpEJe_ufHVVTjQObUAE0',
    appId: '1:1000736909434:android:0fe99f29d826f4d278f3c3',
    messagingSenderId: '1000736909434',
    projectId: 'merchant-pmck',
    storageBucket: 'merchant-pmck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXe30gWdebPS5hdqmPDAF3FVDkg1PHSU8',
    appId: '1:1000736909434:ios:0096f1c9d816e02d78f3c3',
    messagingSenderId: '1000736909434',
    projectId: 'merchant-pmck',
    storageBucket: 'merchant-pmck.appspot.com',
    iosClientId: '1000736909434-2rrpfat5usqqudekt3kl4dm5si9bse9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.rewardz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXe30gWdebPS5hdqmPDAF3FVDkg1PHSU8',
    appId: '1:1000736909434:ios:0096f1c9d816e02d78f3c3',
    messagingSenderId: '1000736909434',
    projectId: 'merchant-pmck',
    storageBucket: 'merchant-pmck.appspot.com',
    iosClientId: '1000736909434-2rrpfat5usqqudekt3kl4dm5si9bse9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.rewardz',
  );
}
